
import java.util.HashMap;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.Timer;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Safari
 */
public final class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
//        initMyComponents();
        
        svgfile="svg/blankMap.svg";
        iconFileName="svg/african_nations_independence.gif";
        
        
        //calling the svgviewer
//        new SVGViewer(mapPanel1, svgfile).view();
//        Level1.pack();
        mySVGViewer=new SVGViewer(mapPanel1, svgfile, Level1);
        mySVGViewer2=new SVGViewer(mapPanel2, svgfile, Level2);
        Level1.pack();
        Level2.pack();

        //Loading icon welcome
        this.drawImageIcon(iconFileName, mapPanel,welcomemapJlbl);
                
        this.pack();
        
        this.fillHashMap();
        this.fillHashHero();
        mySVGViewer.setLb1_1(answer1lbl);
//        System.out.println(" Country Name "+ Country.getRandomCountryName());
        mySVGViewer.setQuestionArea(QuestionArea);
        mySVGViewer2.setQuestionArea2(questionAreaJtxt1);
        mySVGViewer.setQuestionArea2(questionAreaJtxt1);
        mySVGViewer.setLbl1_2(Answer2lbl);
        mySVGViewer.setLbl1_3(Answer3lbl);
        mySVGViewer.setLbl1_4(Answer4lbl);
        mySVGViewer.setLbl1_5(Answer5lbl);
        mySVGViewer.setYourSelection(yourSelection);
        mySVGViewer2.setYourSelection2(yourSelection2);
        mySVGViewer.setYourSelection2(yourSelection2);
        mySVGViewer.setPhotoLabel(heroPhoto);
        mySVGViewer2.setPhotoLabel(heroPhoto);
        mySVGViewer2.setHeroDetails(heroDetails);
        mySVGViewer.setHeroDetails(heroDetails);
        mySVGViewer2.setHeroName(heroName);
        mySVGViewer.setHeroName(heroName);
        mySVGViewer2.setSuccessLbl(successLbl);
        mySVGViewer.setSuccessLbl(successLbl);
        mySVGViewer.setSuccessShot(successShot);
        mySVGViewer2.setSuccessShot(successShot);
        mySVGViewer.setFrameCongrat(Congratulations);
        mySVGViewer2.setFrameCongrat(Congratulations);
        mySVGViewer.setFrameHelp(Help);
        mySVGViewer2.setFrameHelp(Help);
        mySVGViewer2.setCongratLbl(congratLbl);
        mySVGViewer.setCongratLbl(congratLbl);
        
        mySVGViewer.setCongratPanel(congratPanel);
        mySVGViewer2.setCongratPanel(congratPanel);
        
        mySVGViewer.setFrameLevel2(Level2);
        mySVGViewer.setFrameLevel3(Level3);
        
        mySVGViewer.setLbltimer_1(timerLabel);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Level2 = new javax.swing.JFrame();
        mapPanel2 = new javax.swing.JPanel();
        welcomePanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        heroPhoto = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        heroDetails = new javax.swing.JTextArea();
        heroName = new javax.swing.JLabel();
        questionPanel1 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        questionAreaJtxt1 = new javax.swing.JTextArea();
        yourSelection2 = new javax.swing.JLabel();
        successLbl = new javax.swing.JLabel();
        successShot = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        Level3 = new javax.swing.JFrame();
        mapPanel3 = new javax.swing.JPanel();
        welcomePanel3 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        answersAreaJTxt2 = new javax.swing.JTextArea();
        questionPanel2 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        questionAreaJtxt2 = new javax.swing.JTextArea();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        Level1 = new javax.swing.JFrame();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        mapPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        QuestionArea = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        answer1lbl = new javax.swing.JLabel();
        Answer2lbl = new javax.swing.JLabel();
        Answer3lbl = new javax.swing.JLabel();
        Answer5lbl = new javax.swing.JLabel();
        Answer4lbl = new javax.swing.JLabel();
        yourSelection = new javax.swing.JLabel();
        timerLabel = new javax.swing.JLabel();
        Help = new javax.swing.JFrame();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        Congratulations = new javax.swing.JFrame();
        congratPanel = new javax.swing.JPanel();
        congratLbl = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        welcomePanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton12 = new javax.swing.JButton();
        mapPanel = new javax.swing.JPanel();
        welcomemapJlbl = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        copyrightPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        Level2.setTitle("KNOW AFRICA- L2");
        Level2.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                openMain(evt);
            }
        });

        javax.swing.GroupLayout mapPanel2Layout = new javax.swing.GroupLayout(mapPanel2);
        mapPanel2.setLayout(mapPanel2Layout);
        mapPanel2Layout.setHorizontalGroup(
            mapPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 408, Short.MAX_VALUE)
        );
        mapPanel2Layout.setVerticalGroup(
            mapPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("HERO INFORMATION FRAME");

        heroPhoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        heroDetails.setEditable(false);
        heroDetails.setColumns(20);
        heroDetails.setLineWrap(true);
        heroDetails.setRows(3);
        heroDetails.setWrapStyleWord(true);
        jScrollPane3.setViewportView(heroDetails);

        heroName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        heroName.setText("Hero's Name");

        javax.swing.GroupLayout welcomePanel2Layout = new javax.swing.GroupLayout(welcomePanel2);
        welcomePanel2.setLayout(welcomePanel2Layout);
        welcomePanel2Layout.setHorizontalGroup(
            welcomePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(welcomePanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(welcomePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                    .addComponent(heroName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, welcomePanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(heroPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        welcomePanel2Layout.setVerticalGroup(
            welcomePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(welcomePanel2Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(heroPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(heroName, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addContainerGap())
        );

        questionAreaJtxt1.setEditable(false);
        questionAreaJtxt1.setColumns(20);
        questionAreaJtxt1.setLineWrap(true);
        questionAreaJtxt1.setRows(2);
        jScrollPane5.setViewportView(questionAreaJtxt1);

        yourSelection2.setText("Your Selection :");

        successShot.setText("Success Shot :  0");

        javax.swing.GroupLayout questionPanel1Layout = new javax.swing.GroupLayout(questionPanel1);
        questionPanel1.setLayout(questionPanel1Layout);
        questionPanel1Layout.setHorizontalGroup(
            questionPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5)
            .addGroup(questionPanel1Layout.createSequentialGroup()
                .addComponent(yourSelection2, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(successLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(successShot, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
        );
        questionPanel1Layout.setVerticalGroup(
            questionPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(questionPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(questionPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(yourSelection2, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(successLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(successShot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton6.setText("HELP");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("EXIT");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton8.setText("MAIN MENU");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Level2Layout = new javax.swing.GroupLayout(Level2.getContentPane());
        Level2.getContentPane().setLayout(Level2Layout);
        Level2Layout.setHorizontalGroup(
            Level2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Level2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Level2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Level2Layout.createSequentialGroup()
                        .addComponent(questionPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(17, 17, 17))
                    .addGroup(Level2Layout.createSequentialGroup()
                        .addComponent(mapPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(Level2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Level2Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(Level2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(19, 19, 19))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Level2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(welcomePanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
        );
        Level2Layout.setVerticalGroup(
            Level2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Level2Layout.createSequentialGroup()
                .addComponent(questionPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Level2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Level2Layout.createSequentialGroup()
                        .addComponent(welcomePanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Level2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Level2Layout.createSequentialGroup()
                                .addComponent(jButton6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton7))
                            .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(mapPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        Level3.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                openMain(evt);
            }
        });

        javax.swing.GroupLayout mapPanel3Layout = new javax.swing.GroupLayout(mapPanel3);
        mapPanel3.setLayout(mapPanel3Layout);
        mapPanel3Layout.setHorizontalGroup(
            mapPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 348, Short.MAX_VALUE)
        );
        mapPanel3Layout.setVerticalGroup(
            mapPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        answersAreaJTxt2.setEditable(false);
        answersAreaJTxt2.setBackground(new java.awt.Color(240, 240, 240));
        answersAreaJTxt2.setColumns(20);
        answersAreaJTxt2.setLineWrap(true);
        answersAreaJTxt2.setRows(5);
        jScrollPane6.setViewportView(answersAreaJTxt2);

        javax.swing.GroupLayout welcomePanel3Layout = new javax.swing.GroupLayout(welcomePanel3);
        welcomePanel3.setLayout(welcomePanel3Layout);
        welcomePanel3Layout.setHorizontalGroup(
            welcomePanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(welcomePanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        welcomePanel3Layout.setVerticalGroup(
            welcomePanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, welcomePanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
        );

        questionAreaJtxt2.setEditable(false);
        questionAreaJtxt2.setColumns(20);
        questionAreaJtxt2.setRows(5);
        jScrollPane7.setViewportView(questionAreaJtxt2);

        javax.swing.GroupLayout questionPanel2Layout = new javax.swing.GroupLayout(questionPanel2);
        questionPanel2.setLayout(questionPanel2Layout);
        questionPanel2Layout.setHorizontalGroup(
            questionPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        questionPanel2Layout.setVerticalGroup(
            questionPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(questionPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7))
        );

        jButton9.setText("Previous Level");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("Next Level");
        jButton10.setEnabled(false);

        jButton11.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton11.setText("MAIN MENU");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jMenu7.setText("File");
        jMenuBar4.add(jMenu7);

        jMenu8.setText("Edit");
        jMenuBar4.add(jMenu8);

        Level3.setJMenuBar(jMenuBar4);

        javax.swing.GroupLayout Level3Layout = new javax.swing.GroupLayout(Level3.getContentPane());
        Level3.getContentPane().setLayout(Level3Layout);
        Level3Layout.setHorizontalGroup(
            Level3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Level3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Level3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Level3Layout.createSequentialGroup()
                        .addComponent(questionPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(Level3Layout.createSequentialGroup()
                        .addComponent(mapPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(Level3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Level3Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(welcomePanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(Level3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(Level3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(20, Short.MAX_VALUE))))))
        );
        Level3Layout.setVerticalGroup(
            Level3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Level3Layout.createSequentialGroup()
                .addComponent(questionPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Level3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(Level3Layout.createSequentialGroup()
                        .addComponent(welcomePanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(Level3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(Level3Layout.createSequentialGroup()
                                .addComponent(jButton9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton10))
                            .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(mapPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        Level1.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        Level1.setTitle("KNOW AFRICA");
        Level1.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                openMain(evt);
            }
        });

        jButton3.setText("EXIT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("HELP");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton5.setText("MAIN MENU");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        mapPanel1.setLayout(new java.awt.BorderLayout());

        QuestionArea.setEditable(false);
        QuestionArea.setBackground(new java.awt.Color(240, 240, 240));
        QuestionArea.setColumns(20);
        QuestionArea.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 20)); // NOI18N
        QuestionArea.setRows(2);
        QuestionArea.setWrapStyleWord(true);
        QuestionArea.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane1.setViewportView(QuestionArea);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ANSWER CHECK PANEL");

        answer1lbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        answer1lbl.setText("     ");
        answer1lbl.setToolTipText("");

        Answer2lbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Answer2lbl.setText("     ");
        Answer2lbl.setToolTipText("");

        Answer3lbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Answer3lbl.setText("     ");
        Answer3lbl.setToolTipText("");

        Answer5lbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Answer5lbl.setText("     ");
        Answer5lbl.setToolTipText("");

        Answer4lbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Answer4lbl.setText("     ");
        Answer4lbl.setToolTipText("");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(answer1lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Answer2lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Answer3lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Answer5lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Answer4lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(answer1lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Answer2lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Answer3lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Answer4lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Answer5lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        yourSelection.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        yourSelection.setForeground(new java.awt.Color(51, 153, 255));
        yourSelection.setText("Your Selection : ");

        timerLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        timerLabel.setForeground(javax.swing.UIManager.getDefaults().getColor("ToolBar.dockingForeground"));
        timerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        timerLabel.setText("00");

        javax.swing.GroupLayout Level1Layout = new javax.swing.GroupLayout(Level1.getContentPane());
        Level1.getContentPane().setLayout(Level1Layout);
        Level1Layout.setHorizontalGroup(
            Level1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Level1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Level1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 592, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Level1Layout.createSequentialGroup()
                        .addGroup(Level1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(yourSelection, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(mapPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(Level1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(Level1Layout.createSequentialGroup()
                                .addComponent(jButton5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(Level1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(timerLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        Level1Layout.setVerticalGroup(
            Level1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Level1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Level1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(yourSelection, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(timerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Level1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(mapPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(Level1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Level1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Level1Layout.createSequentialGroup()
                                .addComponent(jButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3)))))
                .addContainerGap())
        );

        Help.setTitle("KNOW AFRICA- HELP");

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jTextArea2.setText("LOCATION QUESTION\n\n1. Check the name of the Country to locate in the question Area\n\n2. Click on the location within the map where you think the country is located\n\n3. The system shows your selection. The system generates a new question if your location where right, otherwise, it will give the chance to try 3 times. If you fail to locate in the 3rd time selection, the system saves this question as failed and generates a new question\n\n4. The requirement to pass is three successful location out of 5 questions. If you are equal or above the requiremet, you will pass to the next level, otherwise the system will reset and go back to the welcome window to help you to start a new game.\n\nEnjoy it!");
        jTextArea2.setWrapStyleWord(true);
        jScrollPane4.setViewportView(jTextArea2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("LEVEL 1", jPanel1);

        jTextArea3.setEditable(false);
        jTextArea3.setColumns(20);
        jTextArea3.setLineWrap(true);
        jTextArea3.setRows(5);
        jTextArea3.setText("MATCHING HERO WITH LOCATION OF HIS COUNTRY OF ORIGIN\n\nYou are now a master in locating countries in Africa. This level helps you to know the great sons and daughters of Africa and their country of Origin\n\n1. Check the name of the Hero to match with a country location in the question Area. His/Her picture and a short description are shown on the right side of the panel.\n\n2. Click on the location within the map where you think the country of origin of this hero is located\n\n3. The system shows your selection. The system generates a new question if your location where right, otherwise, it will give the chance to try 3 times. If you fail to locate in the 3rd time selection, the system saves this question as failed and generates a new question\n\n4. The requirement to pass is three successful location out of 5 questions. If you are equal or above the requiremet, you will pass to the next level, otherwise the system will reset and go back to the welcome window to help you to start a new game.\n\nEnjoy it!");
        jTextArea3.setWrapStyleWord(true);
        jScrollPane8.setViewportView(jTextArea3);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("LEVEL 2", jPanel2);

        javax.swing.GroupLayout HelpLayout = new javax.swing.GroupLayout(Help.getContentPane());
        Help.getContentPane().setLayout(HelpLayout);
        HelpLayout.setHorizontalGroup(
            HelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HelpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        HelpLayout.setVerticalGroup(
            HelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HelpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        Congratulations.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        Congratulations.setTitle("CONGRATULATIONS");
        Congratulations.setResizable(false);

        javax.swing.GroupLayout congratPanelLayout = new javax.swing.GroupLayout(congratPanel);
        congratPanel.setLayout(congratPanelLayout);
        congratPanelLayout.setHorizontalGroup(
            congratPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(congratPanelLayout.createSequentialGroup()
                .addComponent(congratLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 14, Short.MAX_VALUE))
        );
        congratPanelLayout.setVerticalGroup(
            congratPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(congratLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jButton13.setText("START OVER");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton14.setText("EXIT");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel5.setText("CONGRATULATIONS !");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("You are now an African ");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("history Master !");

        javax.swing.GroupLayout CongratulationsLayout = new javax.swing.GroupLayout(Congratulations.getContentPane());
        Congratulations.getContentPane().setLayout(CongratulationsLayout);
        CongratulationsLayout.setHorizontalGroup(
            CongratulationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CongratulationsLayout.createSequentialGroup()
                .addComponent(congratPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(CongratulationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                    .addComponent(jButton13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(CongratulationsLayout.createSequentialGroup()
                        .addGroup(CongratulationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jButton14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        CongratulationsLayout.setVerticalGroup(
            CongratulationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(congratPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(CongratulationsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("KNOW AFRICA");
        setResizable(false);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Launch");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(240, 240, 240));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("Welcome to KnowAfrica!\n\nKnow Africa is an educative game that will help you to discover Africa,its rich history and beatiful People.\nGet ready to discover the geography and its great sons/daughters of Africa.");
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane2.setViewportView(jTextArea1);

        jButton12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton12.setText("HOW TO PLAY");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout welcomePanelLayout = new javax.swing.GroupLayout(welcomePanel);
        welcomePanel.setLayout(welcomePanelLayout);
        welcomePanelLayout.setHorizontalGroup(
            welcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(welcomePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(welcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, welcomePanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(welcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, welcomePanelLayout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        welcomePanelLayout.setVerticalGroup(
            welcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, welcomePanelLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton12, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(welcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        mapPanel.setLayout(new java.awt.BorderLayout());

        welcomemapJlbl.setOpaque(true);
        mapPanel.add(welcomemapJlbl, java.awt.BorderLayout.PAGE_START);

        jLabel9.setText("African Countries by Year of Independance");
        mapPanel.add(jLabel9, java.awt.BorderLayout.PAGE_END);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("KnowAfrica V2 (Enhanced) is an Educative game produced as a group assignment.");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Licenced under GNU V2");

        javax.swing.GroupLayout copyrightPanelLayout = new javax.swing.GroupLayout(copyrightPanel);
        copyrightPanel.setLayout(copyrightPanelLayout);
        copyrightPanelLayout.setHorizontalGroup(
            copyrightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(copyrightPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(copyrightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        copyrightPanelLayout.setVerticalGroup(
            copyrightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(copyrightPanelLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2))
        );

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("KNOW AFRICA - AN  EDUCATIVE GAME ABOUT AFRICA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(copyrightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mapPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(welcomePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(welcomePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(mapPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(copyrightPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
//        Level2.setVisible(false);
//        Level1.setVisible(true);
        viewHelp();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        Level3.dispose();
        Level2.setVisible(true);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        initMyComponents();
        
        Level1.pack();
        Level2.pack();
        
        Level1.setVisible(true);
        Level1.setSize(682, 525);
        this.setVisible(false);
        //set the level
        currentLevel=1;
        //reset the question number
        Question.questionNumber=0;
        //call the first question of level1
        currentQuestion=new Question(currentLevel);
        QuestionArea.setText(currentQuestion.generateRandomQuestion());
        
        mySVGViewer.successAnswers=0;
        mySVGViewer2.successAnswers=0;
        mySVGViewer.attempts=0;
        mySVGViewer2.attempts=0;
        
        //Timer launcher
        mySVGViewer.setTime(time);
        mySVGViewer.initTimer();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        Level2.dispose();
        this.setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
       Level3.dispose();
       this.setVisible(true);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Level1.dispose();
//        Level1.removeAll();
        this.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
//       Level1.dispose();
//       Level2.setVisible(true);
//       Level2.setSize(691, 534);
//       nextLevel();
//       questionAreaJtxt1.setText(currentQuestion.generateRandomQuestion());
////       heroDetails.setText();
//       drawHeroImageCurrentQuestion();
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void openMain(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_openMain
        this.setVisible(true);
    }//GEN-LAST:event_openMain

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        this.setVisible(true);
        Congratulations.dispose();
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
       System.out.println("Game terminated by the User");
        System.exit(1);
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        viewHelp();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        viewHelp();
    }//GEN-LAST:event_jButton12ActionPerformed
    public  void drawImageIcon(String iconName,JPanel panel,JLabel label){
//        myIcon= new ImageIcon(iconName);
        ImageIcon myIcon= new ImageIcon(iconName);
        
//        myIcon.getP
        label.setIcon(myIcon);
        
//        panel.add(label);
        panel.repaint();
        
    }
    
//  public 
    
  public void drawHeroImageCurrentQuestion(){
      
          drawImageIcon(dataHashMapHero.get(currentQuestion.getRandomCountryID()).getPhotoURL(), welcomePanel2, heroPhoto);
          heroDetails.setText(dataHashMapHero.get(currentQuestion.getRandomCountryID()).getComments());
          heroName.setText("Name : "+dataHashMapHero.get(currentQuestion.getRandomCountryID()).getFullname());
      
  }

//    /**
//     *
//     */
//    public static void drawHeroPhotoCurrentQuestion(){
//        drawHeroPhotoCurrentQuestion();
//  }
  
  /**
   * Generates the next question 
   * @param level : level of the game
   */
    
  public static void nextQuestion(int level){
      
      currentQuestion=new Question(level);
      
      
  }
  
  public static void nextLevel(){
     currentLevel++;
     Question.questionNumber=0;
      nextQuestion(currentLevel);
     
  }
  
  
  
    
   public void fillHashMap(){
//       dataHashMap.put("ao", new Country("ao", ".ao", "Angola"));
//       dataHashMap.put("za", new Country("za", ".co.za", "South Africa"));
//       dataHashMap.put("cd", new Country("cd", ".cd", "Congo, Democratic Republic of the","Kinshasa","+243",new Hero("Patrice Lumumba", null,"16-1-1961",null)));
//       dataHashMap.put("cg", new Country("cg", ".cg", "Congo, Republic of the"));
       dataHashMap.put("ao", new Country("ao","Angola","Luanda"));
        dataHashMap.put("bf", new Country("bf","Burkina Faso","Ouagadougou"));
        dataHashMap.put("bi", new Country("bi","Burundi","Bujumbura"));
        dataHashMap.put("bj", new Country("bj","Benin","Porto-Novo"));
        dataHashMap.put("bw", new Country("bw","Botswana","Gaborone"));
       dataHashMap.put("cd", new Country("cd", ".cd", "Congo, Democratic Republic of the","Kinshasa","+243",new Hero("Patrice Lumumba", null,"16-1-1961",null)));
        dataHashMap.put("cf", new Country("cf",	"Central African Republic","Bangui"));
        dataHashMap.put("cg", new Country("cg",	"Republic of the Congo","Brazzaville"));
        dataHashMap.put("ci", new Country("ci",	"Ivory Coast","Yamoussoukro"));
        dataHashMap.put("cm", new Country("cm",	"Cameroon","Yaounde"));
        dataHashMap.put("cv", new Country("cv",	"Cape Verde","Praia"));
        dataHashMap.put("dj", new Country("dj",	"Djibouti","Djibouti"));
        dataHashMap.put("dz", new Country("dz",	"Algeria","Algiers"));
        dataHashMap.put("eg", new Country("eg",	"Egypt","Cairo"));
        dataHashMap.put("eh", new Country("eh",	"Western Sahara","El-Aaiun"));
        dataHashMap.put("er", new Country("er",	"Eritrea","Asmara"));
        dataHashMap.put("et", new Country("et",	"Ethiopia","Addis Ababa"));
        dataHashMap.put("ga", new Country("ga",	"Gabon","Libreville"));
        dataHashMap.put("gh", new Country("gh",	"Ghana","Accra"));
        dataHashMap.put("gm", new Country("gm",	"Gambia","Banjul"));
        dataHashMap.put("gn", new Country("gn",	"Guinea","Conakry"));
        dataHashMap.put("gq", new Country("gq","Equatorial Guinea","Malabo"));
        dataHashMap.put("gw", new Country("gw",	"Guinea-Bissau","Bissau"));
        dataHashMap.put("ke", new Country("ke",	"Kenya","Nairobi"));
        dataHashMap.put("km", new Country("km",	"Comoros","Moroni"));
        dataHashMap.put("lr", new Country("lr",	"Liberia","Monrovia"));
        dataHashMap.put("ls", new Country("ls",	"Lesotho","Maseru"));
        dataHashMap.put("ly", new Country("ly",	"Libya","Tripolis"));
        dataHashMap.put("ma", new Country("ma",	"Morocco","Rabat"));
        dataHashMap.put("mg", new Country("mg","Madagascar","Antananarivo"));
        dataHashMap.put("ml", new Country("ml",	"Mali","Bamako"));
        dataHashMap.put("mr", new Country("mr",	"Mauritania","Nouakchott"));
        dataHashMap.put("mu", new Country("mu",	"Mauritius","Port Louis"));
        dataHashMap.put("mw", new Country("mw",	"Malawi","Lilongwe"));
        dataHashMap.put("mz", new Country("mz",	"Mozambique","Maputo"));
        dataHashMap.put("na", new Country("na",	"Namibia","Windhoek"));
        dataHashMap.put("ne", new Country("ne",	"Niger","Niamey"));
        dataHashMap.put("ng", new Country("ng",	"Nigeria","Abuja"));
        dataHashMap.put("re", new Country("re",	"Réunion","Saint-Denis"));
        dataHashMap.put("rw", new Country("rw",	"Rwanda","Kigali"));
        dataHashMap.put("sc", new Country("sc",	"Seychelles","Victoria"));
        dataHashMap.put("sd", new Country("sd",	"Sudan","Khartoum"));
        dataHashMap.put("sh", new Country("sh",	"Saint Helena","Jamestown"));
        dataHashMap.put("sl", new Country("sl",	"Sierra Leone","Freetown"));
        dataHashMap.put("sn", new Country("sn",	"Senegal","Dakar"));
        dataHashMap.put("so", new Country("so",	"Somalia","Mogadishu"));
        dataHashMap.put("ss", new Country("ss",	"South Sudan","Juba"));
        dataHashMap.put("st", new Country("st",	"São Tomé and Príncipe","Sao Tome"));
        dataHashMap.put("sz", new Country("sz",	"Swaziland","Mbabane"));
        dataHashMap.put("td", new Country("td",	"Chad","N'Djamena"));
        dataHashMap.put("tg", new Country("tg",	"Togo","Lome"));
        dataHashMap.put("tn", new Country("tn",	"Tunisia","Tunis"));
        dataHashMap.put("tz", new Country("tz",	"Tanzania","Dodoma"));
        dataHashMap.put("ug", new Country("ug",	"Uganda","Kampala"));
        dataHashMap.put("yt", new Country("yt",	"Mayotte","Mamoudzou"));
        dataHashMap.put("za", new Country("za",	"South Africa","Pretoria"));
        dataHashMap.put("zm", new Country("zm",	"Zambia","Lusaka"));
        dataHashMap.put("zw", new Country("zw","Zimbabwe","Harare"));

       
   }
   
   
   public void fillHashHero(){
 
      dataHashMapHero.put("ke", new Hero("Jomo Kenyatta", "svg/Jomo-Kenyatta_ke.jpg", "ke", "Independance Hero and 1st President"));
      dataHashMapHero.put("gh", new Hero("Koffi Annan", "svg/kofi-annan_gh.jpg", "gh", "Former United Nations Secretary"));
      dataHashMapHero.put("eg", new Hero("Boutros Boutros Gali", "svg/boutros-gali_eg.jpg", "eg", "Former United Nations Secretary"));
      dataHashMapHero.put("ly", new Hero("Muammar Gaddafi", "svg/gaddafi_ly.jpg", "ly", "Revulotionary President, Anti-imperialist and Panafricanist"));
      dataHashMapHero.put("eg", new Hero("Gammal Abdel Nasser", "svg/nasser_eg.jpg", "eg", "Revulotionary President, Anti-imperialist and Panafricanist"));
      dataHashMapHero.put("bf", new Hero("Thomas Sankara", "svg/thomas-sankara_bf.jpg", "bf", "Revulotionary President, Anti-imperialist and Panafricanist"));
      dataHashMapHero.put("zm", new Hero("Kenneth Kaunda", "svg/kenneth-kaunda_zm.jpg", "zm", "Independence Hero,Revulotionary President, Anti-imperialist and Panafricanist"));
      dataHashMapHero.put("mz", new Hero("Samoa Machel", "svg/Samora_Machel_mz.jpg", "zm", "Independence Hero and Anti-imperialist "));
      dataHashMapHero.put("za", new Hero("Frederik W. de Klerk", "svg/F._W._de_Klerk_za.jpg", "za", "Nobel Prize : Apartheid Hero"));
      dataHashMapHero.put("na", new Hero("Sam Nujoma", "svg/Sam-Nujoma_na.jpg", "na", "Independence Hero and 1st President "));
      dataHashMapHero.put("bw", new Hero("Seretse Khama", "svg/SeretseKhama_bw.jpg", "bw", "Independence Hero and 1st President "));
      dataHashMapHero.put("za", new Hero("Desmund Tutu", "svg/tutu_za.jpg", "za", "Apartheid Hero"));
      dataHashMapHero.put("zw", new Hero("Robert Mugabe", "svg/mugabe_zw.jpg", "zw", "Independence Hero and 1st President "));
      dataHashMapHero.put("cd", new Hero("Patrice Lumumba", "svg/lumumba_cd.jpg", "cd", "Independence Hero and Anti-imperialist "));
      dataHashMapHero.put("ke", new Hero("Waangari Maathai", "svg/maathai_ke.jpg", "ke", "Environment Protection Activist "));
      dataHashMapHero.put("za", new Hero("Steve Biko", "svg/stevebiko_za.jpg", "za", "Apartheid Hero and Black Consciousness Activist "));
      dataHashMapHero.put("gh", new Hero("Kuame Nkrumah", "svg/kwame_gh.jpg", "gh", "Independence Hero,Revulotionary President, Anti-imperialist and Panafricanist. Father of African Union "));
      dataHashMapHero.put("tz", new Hero("Julius Nyerere", "svg/julius-nyerere_tz.jpg", "tz", "Revolutionary President, Anti-capitalist and Panafricanist."));
      dataHashMapHero.put("za", new Hero("Nelson Mandela", "svg/mandela_za.jpg", "za", "Apartheid Hero"));
   }
   
   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
               myMain= new MainWindow();
               myMain.setVisible(true);
                
                
            }
        });
    }

    //custom variables
    private final String svgfile;
//    public  Icon myIcon;
    String iconFileName;
    SVGViewer mySVGViewer;
    SVGViewer mySVGViewer2;
    
 //Timer variables
//    Timer timer;
    final static int time=10;
    
    static HashMap<String, Country> dataHashMap=new HashMap();
    static HashMap<String, Hero> dataHashMapHero=new HashMap();
    static Question currentQuestion;
    static int currentLevel;
    final static int requirement=3;
    public static MainWindow myMain;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Answer2lbl;
    private javax.swing.JLabel Answer3lbl;
    private javax.swing.JLabel Answer4lbl;
    private javax.swing.JLabel Answer5lbl;
    private javax.swing.JFrame Congratulations;
    private javax.swing.JFrame Help;
    private javax.swing.JFrame Level1;
    private javax.swing.JFrame Level2;
    private javax.swing.JFrame Level3;
    private javax.swing.JTextArea QuestionArea;
    private javax.swing.JLabel answer1lbl;
    private javax.swing.JTextArea answersAreaJTxt2;
    private javax.swing.JLabel congratLbl;
    private javax.swing.JPanel congratPanel;
    private javax.swing.JPanel copyrightPanel;
    private javax.swing.JTextArea heroDetails;
    private javax.swing.JLabel heroName;
    private javax.swing.JLabel heroPhoto;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JPanel mapPanel;
    private javax.swing.JPanel mapPanel1;
    private javax.swing.JPanel mapPanel2;
    private javax.swing.JPanel mapPanel3;
    private javax.swing.JTextArea questionAreaJtxt1;
    private javax.swing.JTextArea questionAreaJtxt2;
    private javax.swing.JPanel questionPanel1;
    private javax.swing.JPanel questionPanel2;
    private javax.swing.JLabel successLbl;
    private javax.swing.JLabel successShot;
    private javax.swing.JLabel timerLabel;
    private javax.swing.JPanel welcomePanel;
    private javax.swing.JPanel welcomePanel2;
    private javax.swing.JPanel welcomePanel3;
    private javax.swing.JLabel welcomemapJlbl;
    private javax.swing.JLabel yourSelection;
    private javax.swing.JLabel yourSelection2;
    // End of variables declaration//GEN-END:variables

    private void initMyComponents() {
        answer1lbl.setText("");
        answer1lbl.setBorder(null);
        answer1lbl.setIcon(null);
        Answer2lbl.setText("");
        Answer2lbl.setIcon(null);
        Answer2lbl.setBorder(null);
        Answer3lbl.setText("");
        Answer3lbl.setIcon(null);
        Answer3lbl.setBorder(null);
        Answer4lbl.setText("");
        Answer4lbl.setIcon(null);
        Answer4lbl.setBorder(null);
        Answer5lbl.setText("");
        Answer5lbl.setIcon(null);
        Answer5lbl.setBorder(null);
        yourSelection.setText("Your Selection : ");
        yourSelection2.setText("Your Selection : ");
        successShot.setText("Success Shots :  0 ");
        successLbl.setIcon(null);
        successLbl.setBorder(null);
        heroName.setText("");
        heroPhoto.setIcon(null);
        heroDetails.setText("");
        
    }

    private void viewHelp() {
        Help.setVisible(true);
        Help.setSize(625, 395);
    }


}
